language: node_js
os: linux
node_js: lts/*

before_script:
  - npm install
  
script: npm run build-modern

cache:
  directories:
  - node_modules/
  - $HOME/.npm
  
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN
  on:
    all_branches: true
  
  
branches:
  only:
  - deploy
