#import "./OrderDetailsFragment.gql"

mutation OrderLineAdd($id: ID!, $input: OrderLineCreateInput!) {
    draftOrderLineCreate(id: $id, input: $input) {
      errors {
        field
        message
      }
      order {
        ...OrderDetailsFragment
      }
    }
  }
