#import "./OrderDetailsFragment.gql"

mutation OrderLineDelete($id: ID!) {
    draftOrderLineDelete(id: $id) {
      errors {
        field
        message
      }
      order {
        ...OrderDetailsFragment
      }
    }
  }
