#import "./OrderDetailsFragment.gql"

mutation OrderMarkAsPaid($id: ID!) {
    orderMarkAsPaid(id: $id) {
      errors {
        field
        message
      }
      order {
        ...OrderDetailsFragment
      }
    }
  }
