#import "./OrderDetailsFragment.gql"

mutation OrderDraftFinalize($id: ID!) {
    draftOrderComplete(id: $id) {
      errors {
        field
        message
      }
      order {
        ...OrderDetailsFragment
      }
    }
  }
