#import "./MoneyFragment.gql"
#import "./ProductImageFragment.gql"

query ProductList($first: Int, $after: String, $last: Int, $before: String, $priceGte: Float, $priceLte: Float, $query: String, $sortBy: String, $stockAvailability: StockAvailability, $categories: [ID]) {
  products(before: $before, after: $after, first: $first, last: $last, priceGte: $priceGte, priceLte: $priceLte, query: $query, sortBy: $sortBy, stockAvailability: $stockAvailability, categories: $categories) {
    totalCount
    edges {
      node {
        id
        name
        favourite
        description
        seoTitle
        seoDescription
        thumbnailUrl
        category {
          id
          name
        }
        price {
          ...Money
        }
        isPublished
        availableOn
        attributes {
          attribute {
            name
          }
          value {
            name
          }
        }
        availability {
          available
          onSale
          discount {
            net {
              amount
            }
          }
        }
        images {
          edges {
            node {
              ...ProductImage
            }
          }
        }
        variants {
          edges {
            node {
              id
              name
              stockQuantity
              trackInventory
              price {
                ...Money
              }
              availability {
                priceDiscounted {
                  net {
                    amount
                  }
                }
              }
              images {
                edges {
                  node {
                    ...ProductImage
                  }
                }
              }
            }
          }
        }
        url
      }
    }
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
  }
}
