query RootCategoryChildren {
    categories(level: 0) {
      edges {
        cursor
        node {
          id
          name
          children {
            totalCount
          }
          products {
            totalCount
          }
        }
      }
    }
  }
