query RootCategoryChildren {
    categories(level:0, sortBy:"-productsCount"){
      edges {
        cursor
        node {
          id
          name
          products {
            totalCount
          }
        }
      }
    }
  }
